name: Deploy Mule Code to CloudHub 1.0

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    # environment: Production
    env:
      ENV_CLIENT_SECRET: ${{secrets.ENV_CLIENT_SECRET}}
      ENV_CLIENT_ID: ${{secrets.ENV_CLIENT_ID}}
      CONNECTEDAPP_CLIENT_ID: ${{secrets.CONNECTEDAPP_CLIENT_ID}}
      CONNECTEDAPP_CLIENT_SECRET: ${{secrets.CONNECTEDAPP_CLIENT_SECRET}}
      ENCRYPTIO_KEY: ${{secrets.ENCRYPTIO_KEY}}
      MULE_ENV: ${{secrets.MULE_ENV}}
    
    steps:
    - name: Downloading Code
      uses: actions/checkout@v3
    - run: |
        git config user.email "stackmerge@gmail.com"
        git config user.name "stackmerge"
        git config pull.rebase false
        git checkout master
        mvn build-helper:parse-version versions:set -DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion} versions:commit -s settings.xml --file pom.xml
        git add pom.xml
        git commit -m "[skip ci] version updated."
        git push origin master
