name: Deploy Mule Code to CloudHub 1.0

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    environment: Production
    env:
      ENV_CLIENT_SECRET: ${{secrets.ENV_CLIENT_SECRET}}
      ENV_CLIENT_ID: ${{secrets.ENV_CLIENT_ID}}
      CONNECTEDAPP_CLIENT_ID: ${{secrets.CONNECTEDAPP_CLIENT_ID}}
      CONNECTEDAPP_CLIENT_SECRET: ${{secrets.CONNECTEDAPP_CLIENT_SECRET}}
      ENCRYPTIO_KEY: ${{secrets.ENCRYPTIO_KEY}}
      MULE_ENV: ${{secrets.MULE_ENV}}
    
    steps:
    - name: Downloading Code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - run: mvn build-helper:parse-version validate -DbumpPatch -DgenerateBackupPoms=false -s settings.xml --file pom.xml
